### PR TITLE
Optimize workflows

### PR DESCRIPTION
**Pull request by steveiliop56**
Just optimized the workflow a bit (a lot)

### CODE REVIEW

**Comment by sergi0g** [comment]
Wow, great job @steveiliop56! I am terrible at writing Github Action! I'd like 2 more things:
1. There is no need to run a release build in the CI. It would also be very helpful to set up [sccache](https://github.com/cross-rs/cross/wiki/Recipes#sccache) for Cross to ensure faster builds.
2. The build binary CI job failed (https://github.com/sergi0g/cup/actions/runs/10655334162/job/29533707445#step:5:267). Please fix the error.

**Comment by steveiliop56** [comment]
Hello @sergi0g,

I decided not to use cross in the CI as it makes things slower and its not really needed, I instead used `cargo build --verbose` to just build cup to make sure that it works, I guess that eliminates the need for cache since its already quite fast. I also fixed the `mv` command because apparently I forgot to add `./` so it moves it to the current directory. Hope everything is good!

**Comment by sergi0g** [comment]
@steveiliop56 great work! Don't worry about the workflows failing! I'll need to modify the workflow a bit because building Cup now requires the `build.sh` script instead of cargo build. I'll need to modify the Dockerfile too! Thank you so much for this PR!

**Comment by sergi0g** [comment]
@steveiliop56 thank you for your work! I really appreciate the fact that you devoted your time to make DX better.

I want to make a few small changes, so I'll take over from here. Thanks again!

**Comment by steveiliop56** [comment]
No problem have fun!

**Pull request closed without merging**
